[build]
  base = "frontend"
  command = "npm ci && npm list @angular-devkit/build-angular || npm i --save @angular-devkit/build-angular && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" 